### ISSUE TITLE
[Linux] Various errors when building

### ISSUE THREAD

**Issue by adro79** [AcademySoftwareFoundation/OpenRV#15] opened 2023-01-20 20:38 UTC
Hello there,

_Just mention that I have no knowledge of programming and these workaround may cause more problems than fixes. I'm reporting those so anyone with experience can deal with it._

I'm using a fully updated Arch Linux.

```
/home/adro/Applications/3D/OpenRV/src/pub/LibRaw/internal/dcraw_common.cpp:6395:64: error: call of overloaded ‘powf64(int, int)’ is ambiguous
 6395 |                         10*(table_buf[iLensData+9]>>2) * powf64(4, (table_buf[iLensData+9] & 0x03)-2);
      |                                                          ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/12.2.1/cmath:45,
                 from /usr/include/c++/12.2.1/math.h:36,
                 from /home/adro/Applications/3D/OpenRV/src/pub/LibRaw/internal/dcraw_common.cpp:24:
```

A workaround i found is to delete the lines 6392-6395 as mentioned [here](https://github.com/ofnode/of/issues/15#issuecomment-395387638)

Another error I found:
```
/home/adro/Applications/3D/OpenRV/src/lib/app/RvCommon/RvApplication.cpp:855:27: error: ‘sleep_for’ is not a member of ‘std::this_thread’
  855 |         std::this_thread::sleep_for(std::chrono::milliseconds(1));
      |                           ^~~~~~~~~
```
```
/home/adro/Applications/3D/OpenRV/src/bin/apps/rv/main.cpp:431:27: error: ‘sleep_for’ is not a member of ‘std::this_thread’
  431 |         std::this_thread::sleep_for( std::chrono::seconds( sleepTime ) );
      |  
```

As well as the previous one, deleting the line works.

After all this workarounds, I succesfully built OpenRV.

**Comment by marcomeyerVFX** [comment] 2023-01-20 21:24
Had the exact same issues, the (I think)better fix for the first one is described here:
https://github.com/LibRaw/LibRaw/commit/158398653a14e8b5884d744ec711ba31a8ceafdc
so just rename ` powf64(` to ` libraw_powf64(`


For the `sleep_for` errors I had to add `#include <thread>` to both files that throw the error

**Comment by rogernelson** [comment] 2023-01-21 13:30
Great to hear you got it to build on Arch Linux! If this is was the only blocker, I will see if I can do a quick fix that will still work for both Arch and CentOS.

**Comment by adro79** [comment] 2023-01-21 13:41
> Great to hear you got it to build on Arch Linux! If this is was the only blocker, I will see if I can do a quick fix that will still work for both Arch and CentOS.

Well yes, those were the only errors I found.
But I was planning to create an AUR package for OpenRV, and since it requires Qt prebuilt binaries I can't automate the process afaik.

Would be nice to adapt the program to use the system libraries.

**Comment by rogernelson** [comment] 2023-01-24 15:46
It's unfortunately a third-parties library (PySide) that requires a more up-to-date version of Qt than is provided by the system.

**Comment by rogernelson** [comment] 2023-01-24 19:26
With the `ucontext_t` type and `thread` includes addressed, I'll close this issue.  Feel free to reopen if something is not still working.

**Closed by rogernelson** 2023-01-24 19:26 UTC
Labels: build

**Comment by adro79** [comment] 2023-08-01 21:44
Hi, I'm reopening this issue because of the new issues I'm facing when building the current version.

I've had several errors that I've easily patched (due Arch Linux diferences) but I haven't found a way to fix this one:
```
[536/677] Generating /mnt/data/Applications/AUR/openrv/src/build/stage/app/plugins/MovieFormats/movieformats.gto
FAILED: stage/app/plugins/MovieFormats/movieformats.gto /mnt/data/Applications/AUR/openrv/src/build/stage/app/plugins/MovieFormats/movieformats.gto
cd /mnt/data/Applications/AUR/openrv/src/build/stage/app/bin && /mnt/data/Applications/AUR/openrv/src/build/stage/app/bin/makeMovieIOformats /mnt/data/Applications/AUR/openrv/src/build/stage/app/plugins/MovieFormats
RV_HOME = /mnt/data/Applications/AUR/openrv/src/build/stage/app
/mnt/data/Applications/AUR/openrv/src/build/stage/app/bin/makeMovieIOformats.bin: Relink `/mnt/data/Applications/AUR/openrv/src/build/stage/app/lib/liblcms.so' with `/usr/lib/libm.so.6' for IFUNC symbol `sincos'
[542/677] Building CXX object src/lib/ip/IPMu/CMakeFiles/IPMu.dir/CommandsModule.cpp.o
In file included from /mnt/data/Applications/AUR/openrv/src/OpenRV/src/lib/mu/MuLang/MuLang/HalfType.h:14,
                 from /mnt/data/Applications/AUR/openrv/src/OpenRV/src/lib/ip/IPMu/CommandsModule.cpp:46:
/mnt/data/Applications/AUR/openrv/src/deps/RV_DEPS_IMATH/install/include/Imath/halfLimits.h:17:2: warning: #warning "ImathLimits is deprecated; use #include <half.h>" [-Wcpp]
   17 | #warning "ImathLimits is deprecated; use #include <half.h>"
      |  ^~~~~~~
[547/677] Building CXX object src/test/IPCore/AudioRendererTest/CMakeFiles/AudioRendererTest.dir/main.cpp.o
ninja: build stopped: subcommand failed.
```

Once the project gets prebuilt libraries support it would be possible to make an AUR package for OpenRV, but for now I'll keep testing in my machine.

**Comment by meepzh** [comment] 2023-12-09 13:48
Sorry I didn't see this thread before- I'd started an AUR repository since I had an immediate need for OpenRV on Arch earlier https://aur.archlinux.org/packages/openrv-git

It's certainly not the cleanest build, and I haven't been keeping up with every update to the main branch, but I've confirmed that RV's basic functions work, so hopefully it's a good start for people.

**Comment by geffrak** [comment] 2023-12-11 14:14
@meepzh OpenRV contributors are discussing offloading the dependency generation to something like conan so it's done outside of the OpenRV cmake build. It would make it easier for your project since you will be able to grab those dependencies using aur. The plan is not final yet, but so far it's where we are going.

**Comment by geffrak** [comment] 2023-12-11 14:48
Also, @meepzh some of your changes would be great in OpenRV's main repository, would you mind making a pull request?

*  --disable-doc in ffmpeg.cmake
*  the format-security error fix in arg
