### ISSUE TITLE
[Feature]: Update OCIO to v2.2

### ISSUE THREAD

**Issue by tbabiin** [AcademySoftwareFoundation/OpenRV#162] opened 2023-06-05 19:49 UTC
### What happened?

Update OCIO v2.2.1 and update any OCIO dependencies which OCIO needs.

### List all the operating systems versions where this is happening

Windows 10, Windows 11, CentOS 8, Rocky 8, Rocky 9, MacOS 13.2.1

### On what computer hardware is this happening?

All

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rogernelson** [comment] 2023-06-13 20:27
Feature branch created: https://github.com/AcademySoftwareFoundation/OpenRV/tree/feature/162/ocio-update-to-v2

**Comment by dbr** [comment] 2023-09-13 00:28
Hello! Just wondering what the status of this is - the linked PR above is merged, but it is in a feature branch, not the main one?

Having RV with OCIO v2 would be very useful, as it's the last application we are using that is still on v1

**Comment by compaga** [comment] 2023-09-14 12:06
Hi dbr, we are still stabilizing the branch. We currently have confirmed the OCIO v1 config file load and render fine on all three platforms but but we are finding issue with OCIO v2 config file. Specifically on Mac, there are shader error that we need to investigate. Since you seem very interested, if you want to build this branch and help testing it, your help would be more than welcome.

**Comment by herronelou** [comment] 2023-12-11 18:51
Hello.
It seems like the PR has now been merged in main, I was wondering if there are plans to modify the `ocio_source_setup.py` rv package.
OCIO v2, in particular the newer versions, introduced a lot of changes in regards to displays and views, as well as new logic for picking the correct colorspace for different sources via file rules, none of which seems to be taken into account in the OCIO source setup package.
RV in itself has always been a bit awkward to setup for proper OCIO management, particularly for multi-shot timelines (where we tend to need to load a different CDL per shot), so this might be an opportunity to make some improvements, especially since now both RV and OCIO are Autodesk products.

**Comment by geffrak** [comment] 2023-12-20 15:36
@herronelou, the first step was to update the OCIO library being used (keeping the same functionality). The following steps are about using it properly and improving RV with it.

**Comment by BrianHanke** [comment] 2024-01-02 15:45
Happy new year all! I wanted to check in on the status of OCIO. I haven't built RV from source in quite a while, but it sounds from the above discussion that OCIO 2 is at least partially implemented now?

**Comment by compaga** [comment] 2024-04-02 15:48
This feature is completed.

**Closed by compaga** 2024-04-02 15:48 UTC
Labels: enhancement
